name: CI Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch on Push and any branches on PR
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Build Library
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:coverage

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ghiscoding/remove-glob
